# -*- coding: utf-8 -*-
"""SF_robo_advisor_patrimonial0_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vnsta8K4SlBBdgvo7nAZFKPjCLwzj0yx
"""

"""
Proyecto Final: Aplicación de Selección de Portafolios (Robo-Advisor)
Autor: [  SOFIA LIBERTAD FLORES OCHOA]
Descripción: Dashboard interactivo para la asignación de activos
y cálculo de la frontera eficiente de Markowitz.
"""

import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import scipy.optimize as opt
from datetime import datetime, timedelta

st.set_page_config(page_title="Robo-Advisor", layout="wide")

st.title("Robo-Advisor: Optimización de Portafolios")
st.markdown("Aplicación interactiva para la asignación de activos basada en la Frontera Eficiente de Markowitz.")

# Sidebar de configuración
st.sidebar.header("Configuración")

perfil_riesgo = st.sidebar.select_slider(
    "Tolerancia al Riesgo:",
    options=["Muy Conservador", "Conservador", "Moderado", "Agresivo", "Muy Agresivo"],
    value="Moderado"
)

st.sidebar.subheader("Universo de Activos")
opcion_activos = st.sidebar.radio(
    "Mercado:",
    ("ETFs Globales", "Mercado Mexicano (IPC)")
)

if opcion_activos == "ETFs Globales":
    tickers = {
        'Bonos Tesoro (SHV)': 'SHV',
        'Bonos Corp (LQD)': 'LQD',
        'S&P 500 (SPY)': 'SPY',
        'Mercados Emergentes (VWO)': 'VWO'
    }
else:
    tickers = {
        'Walmex': 'WALMEX.MX',
        'America Movil': 'AMXB.MX',
        'Banorte': 'GFNORTEO.MX',
        'Cemex': 'CEMEXCPO.MX'
    }

# Extracción de datos
@st.cache_data
def cargar_datos(tickers_dict):
    lista_tickers = list(tickers_dict.values())
    hoy = datetime.today()
    inicio = hoy - timedelta(days=365*3)

    df = yf.download(lista_tickers, start=inicio, end=hoy, interval="1d")['Close']

    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.droplevel(0)

    df = df.rename(columns={v: k for k, v in tickers_dict.items()})
    return df.dropna()

with st.spinner('Procesando datos y calculando matrices...'):
    precios = cargar_datos(tickers)

    rendimientos_diarios = precios.pct_change().dropna()
    rend_esperado_anual = rendimientos_diarios.mean() * 252
    matriz_cov_anual = rendimientos_diarios.cov() * 252

# Simulacion Monte Carlo
num_portafolios = 10000
num_activos = len(tickers)

pesos_aleatorios = np.random.random((num_portafolios, num_activos))
pesos_aleatorios = pesos_aleatorios / np.sum(pesos_aleatorios, axis=1)[:, np.newaxis]

rendimientos_simulados = np.dot(pesos_aleatorios, rend_esperado_anual)
riesgos_simulados = np.sqrt(np.einsum('ij,jk,ik->i', pesos_aleatorios, matriz_cov_anual.values, pesos_aleatorios))
sharpe_ratios = rendimientos_simulados / riesgos_simulados

# Lógica de perfilamiento
if perfil_riesgo == "Muy Conservador":
    idx_optimo = np.argmin(riesgos_simulados)
elif perfil_riesgo == "Muy Agresivo":
    idx_optimo = np.argmax(rendimientos_simulados)
else:
    riesgo_min = np.min(riesgos_simulados)
    riesgo_max = np.max(riesgos_simulados)

    if perfil_riesgo == "Conservador":
        riesgo_objetivo = riesgo_min + (riesgo_max - riesgo_min) * 0.25
        idx_optimo = np.argmin(np.abs(riesgos_simulados - riesgo_objetivo))
    elif perfil_riesgo == "Moderado":
        idx_optimo = np.argmax(sharpe_ratios)
    elif perfil_riesgo == "Agresivo":
        riesgo_objetivo = riesgo_min + (riesgo_max - riesgo_min) * 0.75
        idx_optimo = np.argmin(np.abs(riesgos_simulados - riesgo_objetivo))

pesos_recomendados = pesos_aleatorios[idx_optimo]
rend_recomendado = rendimientos_simulados[idx_optimo]
riesgo_recomendado = riesgos_simulados[idx_optimo]

# Dashboard UI
col1, col2 = st.columns([2, 1])

with col1:
    st.subheader("Frontera Eficiente")

    fig = go.Figure()

    fig.add_trace(go.Scatter(
        x=riesgos_simulados,
        y=rendimientos_simulados,
        mode='markers',
        marker=dict(color=sharpe_ratios, colorscale='Viridis', showscale=True, size=5, opacity=0.4),
        name='Simulaciones'
    ))

    fig.add_trace(go.Scatter(
        x=[riesgo_recomendado],
        y=[rend_recomendado],
        mode='markers+text',
        marker=dict(color='red', size=12, symbol='star'),
        text=["Portafolio Sugerido"],
        textposition="top center",
        name='Sugerencia'
    ))

    fig.update_layout(xaxis_title="Riesgo (Desviación Estándar)", yaxis_title="Rendimiento Esperado", height=500, template="plotly_white")
    st.plotly_chart(fig, use_container_width=True)

with col2:
    st.subheader("Asignación Óptima")
    st.write(f"**Perfil:** {perfil_riesgo}")

    st.metric(label="Rendimiento Proyectado", value=f"{rend_recomendado*100:.2f}%")
    st.metric(label="Volatilidad", value=f"{riesgo_recomendado*100:.2f}%")

    st.write("**Pesos Sugeridos:**")
    for activo, peso in zip(tickers.keys(), pesos_recomendados):
        st.write(f"- {activo}: {peso*100:.1f}%")

st.markdown("---")
st.subheader("Backtest Histórico (Base 100)")
precios_base100 = (precios / precios.iloc[0]) * 100
st.line_chart(precios_base100)